"""
Unit tests for the frontend HTML generated by chat-frontend-stack.ts.

Extracts the HTML template from the TypeScript source and validates:
- HTML structure and semantics
- Responsive design (viewport meta, media queries, CSS)
- Modern design tokens (CSS custom properties, dark theme)
- All 6 AWS service capabilities
- JavaScript functions and API integration
- Security (XSS escaping, no hardcoded secrets)
- Accessibility basics
- Mobile / tablet / desktop breakpoints
"""

import unittest
import re
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
TS_FILE = os.path.join(ROOT, "lib", "chat-frontend-stack.ts")


def extract_html(ts_source: str) -> str:
    """Extract the HTML template literal from the TypeScript source."""
    idx = ts_source.find("<!DOCTYPE html>")
    end = ts_source.find("</html>", idx)
    if idx == -1 or end == -1:
        raise ValueError("HTML template not found in TypeScript source")
    return ts_source[idx:end + 7]


class TestFrontendHtmlStructure(unittest.TestCase):
    """Tests for basic HTML document structure and semantics."""

    @classmethod
    def setUpClass(cls):
        with open(TS_FILE, encoding="utf-8") as f:
            cls.html = extract_html(f.read())

    def test_doctype_present(self):
        self.assertIn("<!DOCTYPE html>", self.html)

    def test_html_lang_attribute(self):
        self.assertRegex(self.html, r'<html\s+lang="en"')

    def test_charset_utf8(self):
        self.assertRegex(self.html, r'charset=["\']UTF-8["\']')

    def test_viewport_meta(self):
        self.assertIn("width=device-width", self.html)
        self.assertIn("initial-scale=1", self.html)

    def test_page_title(self):
        self.assertIn("<title>AWS Monitor Agent</title>", self.html)

    def test_head_and_body_present(self):
        self.assertIn("<head>", self.html)
        self.assertIn("</head>", self.html)
        self.assertIn("<body>", self.html)
        self.assertIn("</body>", self.html)

    def test_closing_html_tag(self):
        self.assertTrue(self.html.strip().endswith("</html>"))

    def test_style_block_present(self):
        self.assertEqual(self.html.count("<style>"), 1)
        self.assertEqual(self.html.count("</style>"), 1)

    def test_script_block_present(self):
        self.assertEqual(self.html.count("<script>"), 1)
        # closing tag is escaped as <\/script> inside a TS template literal
        self.assertTrue(
            "</script>" in self.html or r"<\/script>" in self.html
        )

    def test_google_fonts_loaded(self):
        self.assertIn("fonts.googleapis.com", self.html)
        self.assertIn("Inter", self.html)
        self.assertIn("JetBrains+Mono", self.html)

    def test_preconnect_hints(self):
        self.assertIn("rel=\"preconnect\"", self.html)


class TestFrontendResponsiveDesign(unittest.TestCase):
    """Tests for responsive / mobile-first design."""

    @classmethod
    def setUpClass(cls):
        with open(TS_FILE, encoding="utf-8") as f:
            cls.html = extract_html(f.read())

    def test_media_query_mobile_600px(self):
        """Must have a breakpoint at or below 600px for mobile."""
        self.assertIn("@media", self.html)
        breakpoints = re.findall(r'max-width:\s*(\d+)px', self.html)
        self.assertTrue(
            any(int(bp) <= 600 for bp in breakpoints),
            f"No mobile breakpoint ≤600px found; breakpoints: {breakpoints}"
        )

    def test_mobile_header_badges_hidden(self):
        """On mobile, header badges are hidden to save space."""
        self.assertIn(".header-badges", self.html)
        # The media query block should mention header-badges
        media_block = re.search(
            r'@media[^{]+\{([^}]*\.header-badges[^}]*)\}', self.html, re.DOTALL
        )
        self.assertIsNotNone(media_block, "header-badges not adjusted in media query")

    def test_mobile_capability_grid_single_column(self):
        """On mobile, capability grid collapses to 1 column."""
        self.assertIn("grid-template-columns: 1fr", self.html)

    def test_mobile_message_wider(self):
        """Messages are wider on mobile (95%) to use screen space."""
        self.assertIn("max-width: 95%", self.html)

    def test_flexbox_layout_body(self):
        """Body uses flexbox column layout."""
        self.assertIn("display: flex", self.html)
        self.assertIn("flex-direction: column", self.html)

    def test_capability_grid_desktop_two_columns(self):
        """Desktop capability grid uses 2 columns."""
        self.assertIn("grid-template-columns: 1fr 1fr", self.html)

    def test_chat_area_scrollable(self):
        """Chat container must be independently scrollable."""
        self.assertIn("overflow-y: auto", self.html)

    def test_textarea_max_height(self):
        """Textarea has max-height to avoid taking full screen on mobile."""
        self.assertIn("max-height", self.html)

    def test_viewport_height_100vh(self):
        """Layout fills full viewport height."""
        self.assertIn("100vh", self.html)

    def test_overflow_hidden_body(self):
        """Body overflow hidden prevents double scrollbars."""
        self.assertIn("overflow: hidden", self.html)


class TestFrontendDesignTokens(unittest.TestCase):
    """Tests for modern CSS design system (custom properties, dark theme)."""

    @classmethod
    def setUpClass(cls):
        with open(TS_FILE, encoding="utf-8") as f:
            cls.html = extract_html(f.read())
        # Extract :root block
        m = re.search(r':root\s*\{([^}]+)\}', cls.html, re.DOTALL)
        cls.root_vars = m.group(1) if m else ""

    def _css_vars(self):
        return re.findall(r'(--[\w-]+):', self.root_vars)

    def test_minimum_css_variables(self):
        """Must define at least 15 CSS custom properties."""
        self.assertGreaterEqual(len(self._css_vars()), 15)

    def test_color_palette_defined(self):
        for var in ("--bg", "--surface", "--border", "--accent", "--text"):
            self.assertIn(var, self.root_vars, f"Missing CSS var: {var}")

    def test_dark_background(self):
        """Background color must be a dark hex (starts with #0 or #1)."""
        bg_match = re.search(r'--bg:\s*(#[0-9a-fA-F]+)', self.root_vars)
        self.assertIsNotNone(bg_match, "--bg color not found")
        bg_hex = bg_match.group(1)
        self.assertRegex(bg_hex, r'^#[01]', f"Background not dark enough: {bg_hex}")

    def test_aws_orange_accent(self):
        """Accent color should use AWS orange (#ff9900)."""
        self.assertIn("#ff9900", self.html.lower())

    def test_semantic_color_vars(self):
        """Must define green, red, yellow for status indicators."""
        for var in ("--green", "--red", "--yellow"):
            self.assertIn(var, self.root_vars)

    def test_border_radius_defined(self):
        self.assertIn("--radius", self.root_vars)

    def test_transition_var(self):
        self.assertIn("--transition", self.root_vars)

    def test_font_stack_defined(self):
        self.assertIn("--font", self.root_vars)
        self.assertIn("--mono", self.root_vars)

    def test_animations_defined(self):
        animations = re.findall(r'@keyframes\s+(\w+)', self.html)
        self.assertGreaterEqual(len(animations), 3,
                                f"Expected ≥3 animations, found: {animations}")
        self.assertIn("fadeIn", animations)
        self.assertIn("bounce", animations)


class TestFrontendComponents(unittest.TestCase):
    """Tests for presence and correctness of UI components."""

    @classmethod
    def setUpClass(cls):
        with open(TS_FILE, encoding="utf-8") as f:
            cls.html = extract_html(f.read())

    def test_header_component(self):
        self.assertIn("<header>", self.html)
        self.assertIn("</header>", self.html)

    def test_logo_element(self):
        self.assertIn('class="logo"', self.html)

    def test_header_shows_multi_region(self):
        # Header now shows multi-region capability instead of fixed us-east-1
        self.assertTrue(
            "Multi-regi" in self.html or "multi-regi" in self.html,
            "Header should indicate multi-region support"
        )

    def test_placeholder_mentions_region_example(self):
        self.assertIn("eu-west-1", self.html)

    def test_header_badges_for_all_services(self):
        for service in ("EC2", "Lambda", "CloudWatch", "Logs Insights", "X-Ray"):
            self.assertIn(service, self.html, f"Service badge missing: {service}")

    def test_status_dot_animated(self):
        self.assertIn("status-dot", self.html)
        self.assertIn("pulse-dot", self.html)

    def test_welcome_card_present(self):
        self.assertIn('class="welcome-card"', self.html)

    def test_capability_grid_six_items(self):
        count = self.html.count('class="cap-item"')
        self.assertGreaterEqual(count, 6,
                                f"Expected ≥6 cap-items, found {count}")

    def test_all_six_capabilities_named(self):
        for cap in ("Salud General", "EC2", "Lambda", "CloudWatch",
                    "Logs Insights", "X-Ray"):
            self.assertIn(cap, self.html, f"Capability card missing: {cap}")

    def test_chat_container(self):
        self.assertIn('id="chat"', self.html)

    def test_typing_indicator_component(self):
        self.assertIn("typing-indicator", self.html)
        self.assertIn('class="typing"', self.html)

    def test_six_suggestion_buttons(self):
        count = self.html.count("sendSuggestion(")
        self.assertGreaterEqual(count, 6,
                                f"Expected ≥6 suggestion buttons, found {count}")

    def test_suggestion_covers_logs_analysis(self):
        self.assertRegex(self.html, r'(?i)(logs|analiz)', )

    def test_suggestion_covers_xray(self):
        self.assertRegex(self.html, r'(?i)(X-Ray|xray|trazas)', )

    def test_footer_input_bar(self):
        self.assertIn('class="footer-bar"', self.html)
        self.assertIn("<textarea", self.html)

    def test_send_button_with_svg_icon(self):
        self.assertIn('class="send-btn"', self.html)
        self.assertIn("<svg", self.html)

    def test_char_counter(self):
        self.assertIn('id="charCount"', self.html)

    def test_session_info_element(self):
        self.assertIn('id="sessionInfo"', self.html)

    def test_toast_component(self):
        # Toast is created dynamically via JS; CSS class and animation must be defined
        self.assertIn(".toast", self.html)      # CSS rule exists
        self.assertIn("toast-in", self.html)    # animation keyframe exists
        self.assertIn("showToast", self.html)   # JS function referenced

    def test_custom_scrollbar_styling(self):
        self.assertIn("::-webkit-scrollbar", self.html)

    def test_message_user_and_assistant_styles(self):
        self.assertIn(".message.user", self.html)
        self.assertIn(".message.assistant", self.html)

    def test_code_block_styling(self):
        self.assertIn(".bubble pre", self.html)
        self.assertIn(".bubble code", self.html)

    def test_status_color_spans(self):
        self.assertIn(".status-ok", self.html)
        self.assertIn(".status-warn", self.html)
        self.assertIn(".status-crit", self.html)


class TestFrontendJavaScript(unittest.TestCase):
    """Tests for JavaScript logic and API integration."""

    @classmethod
    def setUpClass(cls):
        with open(TS_FILE, encoding="utf-8") as f:
            cls.html = extract_html(f.read())

    def _js_section(self):
        start = self.html.find("<script>")
        end   = self.html.find("</script>") if "</script>" in self.html \
                else self.html.find(r"<\/script>")
        return self.html[start:end] if start != -1 else ""

    def test_all_required_functions_defined(self):
        js = self._js_section()
        for fn in ("sendMessage", "sendSuggestion", "appendMessage",
                   "showTyping", "removeTyping", "formatMarkdown",
                   "escapeHtml", "showToast"):
            self.assertIn(fn, js, f"JS function missing: {fn}")

    def test_api_url_uses_template_variable(self):
        self.assertIn("${apiUrl}", self.html)

    def test_api_key_runtime_configurable(self):
        # API key is now loaded at runtime (sessionStorage/URL hash), not hardcoded
        self.assertIn("aws_monitor_api_key", self.html)
        self.assertNotIn("%%API_KEY_PLACEHOLDER%%", self.html)

    def test_no_hardcoded_api_key(self):
        """API key must be a placeholder, not a real key (starts with AKIA)."""
        self.assertNotRegex(self.html, r'AKIA[A-Z0-9]{16}')

    def test_fetch_post_method(self):
        self.assertIn("method: 'POST'", self.html)

    def test_json_content_type_header(self):
        self.assertIn("application/json", self.html)

    def test_x_api_key_header_sent(self):
        self.assertIn("x-api-key", self.html)

    def test_session_id_generated(self):
        self.assertIn("sessionId", self.html)
        self.assertIn("Math.random()", self.html)

    def test_enter_key_sends_message(self):
        self.assertIn("'Enter'", self.html)
        self.assertIn("shiftKey", self.html)

    def test_shift_enter_allows_newline(self):
        js = self._js_section()
        self.assertIn("!e.shiftKey", js)

    def test_textarea_auto_resize(self):
        js = self._js_section()
        self.assertIn("scrollHeight", js)

    def test_send_button_disabled_while_busy(self):
        js = self._js_section()
        self.assertIn("sendBtn.disabled = true", js)
        self.assertIn("sendBtn.disabled = false", js)

    def test_char_limit_validation(self):
        js = self._js_section()
        self.assertIn("2000", js)

    def test_xss_escape_html(self):
        """User input must go through escapeHtml to prevent XSS."""
        js = self._js_section()
        self.assertIn("escapeHtml", js)
        self.assertIn("replace(/</g", js)
        self.assertIn("replace(/>/g", js)

    def test_markdown_formatting(self):
        js = self._js_section()
        self.assertIn("formatMarkdown", js)
        # Bold **text**
        self.assertIn("<strong>", js)
        # Code blocks
        self.assertIn("<pre><code>", js)

    def test_typing_indicator_shown_and_removed(self):
        js = self._js_section()
        self.assertIn("showTyping()", js)
        self.assertIn("removeTyping()", js)

    def test_error_handling_try_catch(self):
        js = self._js_section()
        self.assertIn("try {", js)
        self.assertIn("catch", js)

    def test_status_label_updated_during_request(self):
        js = self._js_section()
        self.assertIn("statusLabel", js)

    def test_suggestions_hidden_after_first_message(self):
        js = self._js_section()
        self.assertIn("suggestions", js)
        self.assertIn("display = 'none'", js)

    def test_session_id_updated_from_response(self):
        js = self._js_section()
        self.assertIn("data.sessionId", js)


class TestFrontendSecurity(unittest.TestCase):
    """Tests for security best practices in the frontend."""

    @classmethod
    def setUpClass(cls):
        with open(TS_FILE, encoding="utf-8") as f:
            cls.html = extract_html(f.read())

    def test_no_inline_event_xss_risk(self):
        """All onclick handlers only call internal functions, not eval."""
        onclick_vals = re.findall(r'onclick="([^"]+)"', self.html)
        for val in onclick_vals:
            self.assertNotIn("eval(", val)
            self.assertNotIn("document.write", val)

    def test_no_hardcoded_aws_account(self):
        """Account ID in the UI info text is acceptable but no secrets."""
        self.assertNotRegex(self.html, r'AKIA[A-Z0-9]{16}')

    def test_no_hardcoded_secret_key(self):
        """No AWS secret key pattern."""
        self.assertNotRegex(self.html, r'[A-Za-z0-9/+=]{40}')

    def test_xss_prevention_in_user_bubbles(self):
        """User messages use escapeHtml, not innerHTML directly."""
        js_start = self.html.find("<script>")
        js = self.html[js_start:]
        # escapeHtml is called for user role
        self.assertIn("escapeHtml(text)", js)

    def test_api_url_relative_to_deployment(self):
        """API URL is injected via CDK, not hardcoded."""
        self.assertIn("${apiUrl}", self.html)
        self.assertNotRegex(self.html, r'https://[a-z0-9]+\.execute-api\.')


class TestFrontendAccessibility(unittest.TestCase):
    """Tests for basic accessibility requirements."""

    @classmethod
    def setUpClass(cls):
        with open(TS_FILE, encoding="utf-8") as f:
            cls.html = extract_html(f.read())

    def test_lang_attribute_on_html(self):
        self.assertIn('lang="en"', self.html)

    def test_title_element_present(self):
        self.assertIn("<title>", self.html)

    def test_button_has_title_attribute(self):
        send_btn = re.search(r'<button[^>]*id="send"[^>]*>', self.html)
        self.assertIsNotNone(send_btn)
        self.assertIn("title=", send_btn.group(0))

    def test_textarea_has_placeholder(self):
        self.assertIn("placeholder=", self.html)

    def test_contrast_dark_theme(self):
        """Text color should be near-white on dark background."""
        text_match = re.search(r'--text:\s*(#[0-9a-fA-F]+)', self.html)
        self.assertIsNotNone(text_match)
        hex_val = text_match.group(1).lstrip('#')
        r = int(hex_val[0:2], 16)
        self.assertGreater(r, 180, f"Text color not bright enough for dark bg: #{hex_val}")

    def test_focus_styles_present(self):
        """Input must have visible focus indicator."""
        self.assertIn(":focus", self.html)

    def test_font_size_readable(self):
        """Base font size should be ≥13px."""
        sizes = re.findall(r'font-size:\s*(\d+(?:\.\d+)?)px', self.html)
        base_sizes = [float(s) for s in sizes]
        self.assertTrue(
            any(s >= 13 for s in base_sizes),
            f"No font-size ≥ 13px found. Sizes: {base_sizes}"
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)